### ISSUE TITLE
Broken link - Cannot find URL

### ISSUE THREAD

**Issue by zhemingfan** [PavlidisLab/ermineR#21]
I was trying to run 

```
oraOut = ora(annotation = 'Generic_human',
             hitlist = hitlist)
```

And I am getting an error of:

```
cannot open URL 'http://release.geneontology.org/latest-termdb/go_daily-termdb.rdf-xml.gz': HTTP status was '404 Not Found'Error in utils::download.file("http://archive.geneontology.org/latest-termdb/go_daily-termdb.rdf-xml.gz",  : 
  cannot open URL 'http://archive.geneontology.org/latest-termdb/go_daily-termdb.rdf-xml.gz'
```

**Comment by oganm** [comment]
Sorry for the delay. Will have to switch to obo support it seems.

Related issue https://github.com/geneontology/helpdesk/issues/302

**Comment by oganm** [comment]
A temporary fix for this would be to use a file path to an xml file. An old one is provided in this repository [here](https://github.com/PavlidisLab/ermineR/blob/master/tests/testthat/testFiles/Go.xml)

**Comment by oganm** [comment]
All ermineR functions should now work fine with the new files and their links
