### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by Nayrouz109** [PavlidisLab/ermineR#22]
Hey Ogan, 

I am still having issues running ermineR functions. To try and solve the problem with the annotation file, I thought I could create my own file and then use it. But I kept getting the below error: 

`Error in (function (annotation = NULL, aspects = c("Molecular Function", : Something went wrong. Blame the dev sh: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/ermineR/ermineJ-3.2/bin/ermineJ.sh: Permission denied`

Any help would be greatly appreciated! 
Thanks

**Comment by oganm** [comment]
It seems like the file doesn't have running persmissions. it happens on occasion. doing

```
chmod +x /Library/Frameworks/R.framework/Versions/4.1/Resources/library/ermineR/ermineJ-3.1.2/bin/ermineJ.sh
```

should fix it. you may have to use sudo if you don't have the right privileges on the directory

**Comment by Nayrouz109** [comment]
That fixes it!! Thanks much Ogan.
