### ISSUE TITLE
Is it possible to download the gene to function table without using the statistical procedure in the package?

### ISSUE THREAD

**Issue by garyzhubc** [PavlidisLab/ermineR#23]
Is it possible to download the gene to function table without using the statistical procedure in the package?

For instance, it will be a table like:

           Function1 Function2

Gene1       x

Gene2       x                x

that I would want.

**Comment by oganm** [comment]
The data needed for this would be available in the annotation files that you can get by `gemma.R::get_platform_annotations` function.

for example

```r
annot = get_platform_annotations('GPL96')
annot = annot %>% dplyr::select(GeneSymbols,GOTerms) %>% unique
gene_gos = annot$GOTerms %>% strsplit('\\|')
all_gos = unique(unlist(gene_gos))


matrix = lapply(seq_len(nrow(annot)),function(i){
    all_gos %in% gene_gos[[i]]
}) %>% do.call(rbind,.)

rownames(matrix) = annot$GeneSymbols
colnames(matrix) = all_gos

```
